### ISSUE TITLE
version 2.0 failed during errands deploy-all

### ISSUE THREAD

**Issue by yanivbhemo** [thecodeteam/ecs-cf-service-broker#144]
Hello,
Recently I deployed VMware Tanzu TAS (PAS) 2.9 over vSphere 6.7 .
During ECS service broker deployment, after the installation went successfully, I receive an error at the **errands stage** :
'Unknown failure reason. missing ['snapshot', 'datastore'] '
The VM gets created and immediately after the failure at the errands stage it gets deleted.

Any ideas maybe?
Thank you!!

**Comment by rogalv** [comment]
Hello yanivbhemo,

this looks to be a VCenter configuration issue. A search on Pivotal Network gives similar case for missing snapshot:

https://community.pivotal.io/s/article/BOSH-Command-Shows-the-Error-The-objects-VimVirtualMachine-vm-5521-should-have-the-following-properties-snapshot?language=en_US
https://community.pivotal.io/s/article/BOSH-Recreate-Tasks-Queueing-and-Failing-with-Snapshot-Missing-Errors?language=en_US

**Comment by yanivbhemo** [comment]
Thank you. It worked!
