### ISSUE TITLE
Version 2.0 deployment failed during errands

### ISSUE THREAD

**Issue by yanivbhemo** [thecodeteam/ecs-cf-service-broker#146]
Following issue:
Application run failed
BeanCreationException: Error creating bean with name ‘ecsService’: Invocation of init method failed;

Failed to make a call to ecs.example.com:4443/vdc/data-service/vpools:
unknown protocol: ecs.example.com

**VM deployed, org, space and app deployed to PAS but after 3 failures in starting up the app the deployment fails**

Thank You!

**Comment by rogalv** [comment]
Hi yanivbhemo,
Review broker settings: ECS Management Endpoint value should be a full URI with protocol schema:
https://ecs.example.com:4443

**Comment by yanivbhemo** [comment]
Unfortunately didn’t work.
According to logs it appears that it do not parse the login correctly and therefore the rest of commands do not work.
I am using ecs version 3.2 is might be the issue?

**Comment by rogalv** [comment]
Could you put logs excerpt here? What is the error related to login?
And - is ecs.example.com the URL in the config, or you had masked real value?

**Comment by yanivbhemo** [comment]
Hi,
Upgrade ECS to 3.4 fixed the issue.
Thanks!
