### ISSUE TITLE
Ability to choose replication group and/or namespace during bucket (service) creation?

### ISSUE THREAD

**Issue by yanivbhemo** [thecodeteam/ecs-cf-service-broker#159]
Hi,
Is there an ability to choose replication group and/or namespace during bucket (service) creation?

Thanks!

**Comment by rogalv** [comment]
Replication group could be specified in both catalog definition and in create request options, see "replication-group" parameter in table:
https://github.com/thecodeteam/ecs-cf-service-broker#broker-catalog-and-plan-configuration
