### ISSUE TITLE
ECS Object Endpoint without Port specified

### ISSUE THREAD

**Issue by vchrisb** [thecodeteam/ecs-cf-service-broker#86]
When configuring the ECS Object Endpoint without a port like `https://ecs.domain.com` will result in a malformed s3Url in the binding information. `"s3Url": "https://abcde:fghijk@ecs.domain.com:-1/bucket` 

[getS3Url Line 73](https://github.com/codedellemc/ecs-cf-service-broker/blob/master/src/main/java/com/emc/ecs/cloudfoundry/broker/service/NamespaceBindingWorkflow.java#L73)

**Comment by spiegela** [comment]
@vchrisb Thanks for spotting this. I had just found it myself. I have a PR in progress to fix.

**Comment by spiegela** [comment]
@vchrisb I think this issue is resolved. I added some unit tests and tested before S1P. Would you mind testing in your environment and validating this is resolved for you?

Thanks!

**Comment by spiegela** [comment]
@clintkitson I think this issue can be closed. It was just waiting on user validation. Somehow I don't have the ability to close it myself anymore.
